import { Product } from './store';

export type { Product };

export const categories = [
  'Electronics',
  'Fashion',
  'Home & Kitchen',
  'Beauty & Personal Care',
  'Sports & Fitness',
  'Books & Media',
  'Automotive',
  'Health & Wellness'
];

export const brands = [
  'Samsung',
  'Apple',
  'OnePlus',
  'Xiaomi',
  'Realme',
  'Vivo',
  'Oppo',
  'Boat',
  'JBL',
  'Sony',
  'LG',
  'Whirlpool',
  'IFB',
  'Godrej',
  'Bajaj',
  'Philips',
  'Havells',
  'Asian Paints',
  'Nippon Paint',
  'Berger Paints',
  'Nike',
  'Adidas',
  'Puma',
  'Reebok',
  'Levi\'s',
  'H&M',
  'Zara',
  'Lakme',
  'Maybelline',
  'L\'Oreal'
];

export const sampleProducts: Product[] = [
  // Electronics
  {
    id: '1',
    name: 'Samsung Galaxy S23 Ultra',
    price: 124999,
    originalPrice: 149999,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg',
    category: 'Electronics',
    brand: 'Samsung',
    rating: 4.5,
    reviews: 2847,
    description: 'Premium flagship smartphone with S Pen, 200MP camera, and powerful performance for professionals and creators.',
    features: ['200MP Camera', 'S Pen Support', '12GB RAM', '256GB Storage', '5000mAh Battery'],
    inStock: true,
    discount: 17
  },
  {
    id: '2',
    name: 'Apple iPhone 15 Pro',
    price: 134900,
    originalPrice: 134900,
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg',
    category: 'Electronics',
    brand: 'Apple',
    rating: 4.8,
    reviews: 1923,
    description: 'Latest iPhone with titanium design, Action Button, and advanced camera system for photography enthusiasts.',
    features: ['Titanium Design', 'A17 Pro Chip', '48MP Main Camera', 'Action Button', 'USB-C'],
    inStock: true
  },
  {
    id: '3',
    name: 'OnePlus 11 5G',
    price: 56999,
    originalPrice: 61999,
    image: 'https://images.pexels.com/photos/1440727/pexels-photo-1440727.jpeg',
    category: 'Electronics',
    brand: 'OnePlus',
    rating: 4.4,
    reviews: 3421,
    description: 'Flagship killer with Snapdragon 8 Gen 2, Hasselblad cameras, and 100W fast charging technology.',
    features: ['Snapdragon 8 Gen 2', 'Hasselblad Cameras', '16GB RAM', '100W Fast Charging'],
    inStock: true,
    discount: 8
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5 Headphones',
    price: 29990,
    originalPrice: 34990,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
    category: 'Electronics',
    brand: 'Sony',
    rating: 4.7,
    reviews: 1567,
    description: 'Industry-leading noise canceling wireless headphones with exceptional sound quality and comfort.',
    features: ['Active Noise Canceling', '30hr Battery', 'Quick Charge', 'Multipoint Connection'],
    inStock: true,
    discount: 14
  },
  {
    id: '5',
    name: 'LG 55" OLED C3 Smart TV',
    price: 134990,
    originalPrice: 154990,
    image: 'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg',
    category: 'Electronics',
    brand: 'LG',
    rating: 4.6,
    reviews: 892,
    description: '4K OLED Smart TV with perfect blacks, vibrant colors, and advanced gaming features for entertainment.',
    features: ['4K OLED Display', 'webOS Smart TV', 'Gaming Mode', 'Dolby Vision IQ'],
    inStock: true,
    discount: 13
  },
  {
    id: '6',
    name: 'Boat Airdopes 800 TWS',
    price: 4999,
    originalPrice: 7999,
    image: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg',
    category: 'Electronics',
    brand: 'Boat',
    rating: 4.2,
    reviews: 5634,
    description: 'True wireless earbuds with active noise cancellation and long battery life for music lovers.',
    features: ['ANC Technology', '35hr Playback', 'Fast Charging', 'IPX7 Water Resistant'],
    inStock: true,
    discount: 38
  },
  {
    id: '7',
    name: 'Xiaomi Mi 11X Pro',
    price: 39999,
    originalPrice: 44999,
    image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg',
    category: 'Electronics',
    brand: 'Xiaomi',
    rating: 4.3,
    reviews: 2156,
    description: 'Powerful smartphone with Snapdragon 888, 108MP camera, and 120Hz AMOLED display.',
    features: ['Snapdragon 888', '108MP Camera', '8GB RAM', '120Hz Display', '4520mAh Battery'],
    inStock: true,
    discount: 11
  },
  {
    id: '8',
    name: 'JBL Charge 5 Bluetooth Speaker',
    price: 12999,
    originalPrice: 15999,
    image: 'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg',
    category: 'Electronics',
    brand: 'JBL',
    rating: 4.5,
    reviews: 3421,
    description: 'Portable Bluetooth speaker with powerful sound, waterproof design, and power bank feature.',
    features: ['20hr Playtime', 'IP67 Waterproof', 'Power Bank', 'JBL Pro Sound'],
    inStock: true,
    discount: 19
  },

  // Fashion
  {
    id: '9',
    name: 'Levi\'s 511 Slim Fit Jeans',
    price: 3999,
    originalPrice: 4999,
    image: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
    category: 'Fashion',
    brand: 'Levi\'s',
    rating: 4.4,
    reviews: 1876,
    description: 'Classic slim fit jeans with premium denim fabric and comfortable stretch for everyday wear.',
    features: ['Slim Fit', 'Stretch Denim', 'Classic 5-Pocket', 'Machine Washable'],
    inStock: true,
    discount: 20
  },
  {
    id: '10',
    name: 'Nike Air Max 270 Sneakers',
    price: 12995,
    originalPrice: 14995,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg',
    category: 'Fashion',
    brand: 'Nike',
    rating: 4.6,
    reviews: 2341,
    description: 'Lifestyle sneakers with Max Air unit for all-day comfort and modern street style.',
    features: ['Max Air Cushioning', 'Mesh Upper', 'Rubber Outsole', 'Lifestyle Design'],
    inStock: true,
    discount: 13
  },
  {
    id: '11',
    name: 'H&M Cotton T-Shirt',
    price: 799,
    originalPrice: 999,
    image: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    category: 'Fashion',
    brand: 'H&M',
    rating: 4.2,
    reviews: 5432,
    description: 'Comfortable cotton t-shirt with regular fit and soft fabric for casual everyday wear.',
    features: ['100% Cotton', 'Regular Fit', 'Crew Neck', 'Machine Washable'],
    inStock: true,
    discount: 20
  },
  {
    id: '12',
    name: 'Adidas Originals Hoodie',
    price: 4999,
    originalPrice: 5999,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    category: 'Fashion',
    brand: 'Adidas',
    rating: 4.5,
    reviews: 1654,
    description: 'Classic hoodie with iconic 3-Stripes design and comfortable fleece lining for warmth.',
    features: ['Fleece Lining', '3-Stripes Design', 'Kangaroo Pocket', 'Ribbed Cuffs'],
    inStock: true,
    discount: 17
  },

  // Home & Kitchen
  {
    id: '13',
    name: 'Whirlpool 7.5 Kg Washing Machine',
    price: 24990,
    originalPrice: 29990,
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg',
    category: 'Home & Kitchen',
    brand: 'Whirlpool',
    rating: 4.3,
    reviews: 876,
    description: 'Fully automatic top load washing machine with multiple wash programs and energy efficiency.',
    features: ['7.5 Kg Capacity', '12 Wash Programs', 'Energy Efficient', '2 Year Warranty'],
    inStock: true,
    discount: 17
  },
  {
    id: '14',
    name: 'LG 260L Double Door Refrigerator',
    price: 28990,
    originalPrice: 32990,
    image: 'https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg',
    category: 'Home & Kitchen',
    brand: 'LG',
    rating: 4.4,
    reviews: 1234,
    description: 'Energy efficient double door refrigerator with smart inverter compressor and spacious storage.',
    features: ['260L Capacity', 'Smart Inverter', 'Multi Air Flow', '10 Year Warranty'],
    inStock: true,
    discount: 12
  },
  {
    id: '15',
    name: 'Bajaj Majesty RX11 OTG',
    price: 6999,
    originalPrice: 8999,
    image: 'https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg',
    category: 'Home & Kitchen',
    brand: 'Bajaj',
    rating: 4.2,
    reviews: 2156,
    description: 'Versatile oven toaster griller with multiple cooking functions and temperature control.',
    features: ['35L Capacity', 'Convection Cooking', 'Timer Control', 'Multiple Functions'],
    inStock: true,
    discount: 22
  },
  {
    id: '16',
    name: 'Philips Air Fryer HD9252',
    price: 12995,
    originalPrice: 15995,
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg',
    category: 'Home & Kitchen',
    brand: 'Philips',
    rating: 4.6,
    reviews: 3421,
    description: 'Healthy cooking air fryer with rapid air technology for oil-free crispy food preparation.',
    features: ['4.1L Capacity', 'Rapid Air Technology', 'Digital Display', 'Dishwasher Safe'],
    inStock: true,
    discount: 19
  },

  // Beauty & Personal Care
  {
    id: '17',
    name: 'Lakme Absolute Perfect Radiance Foundation',
    price: 1350,
    originalPrice: 1500,
    image: 'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg',
    category: 'Beauty & Personal Care',
    brand: 'Lakme',
    rating: 4.3,
    reviews: 2876,
    description: 'Long-lasting liquid foundation with SPF protection and natural radiant finish.',
    features: ['SPF 20', 'Long Lasting', 'Natural Finish', 'Multiple Shades'],
    inStock: true,
    discount: 10
  },
  {
    id: '18',
    name: 'Maybelline New York Mascara',
    price: 599,
    originalPrice: 699,
    image: 'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg',
    category: 'Beauty & Personal Care',
    brand: 'Maybelline',
    rating: 4.4,
    reviews: 4321,
    description: 'Volumizing mascara for dramatic lashes with smudge-proof and long-wearing formula.',
    features: ['Volumizing', 'Smudge Proof', 'Long Wearing', 'Easy Application'],
    inStock: true,
    discount: 14
  },
  {
    id: '19',
    name: 'L\'Oreal Paris Hair Serum',
    price: 450,
    originalPrice: 550,
    image: 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
    category: 'Beauty & Personal Care',
    brand: 'L\'Oreal',
    rating: 4.2,
    reviews: 1876,
    description: 'Nourishing hair serum for smooth, shiny hair with heat protection and frizz control.',
    features: ['Heat Protection', 'Frizz Control', 'Shine Enhancement', 'All Hair Types'],
    inStock: true,
    discount: 18
  },
  {
    id: '20',
    name: 'Philips Norelco Electric Shaver',
    price: 8999,
    originalPrice: 10999,
    image: 'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
    category: 'Beauty & Personal Care',
    brand: 'Philips',
    rating: 4.5,
    reviews: 1543,
    description: 'Advanced electric shaver with precision cutting system and comfortable grip design.',
    features: ['Precision Cutting', 'Wet & Dry Use', 'Long Battery Life', 'Easy Cleaning'],
    inStock: true,
    discount: 18
  },

  // Sports & Fitness
  {
    id: '21',
    name: 'Nike Dri-FIT Running Shorts',
    price: 2495,
    originalPrice: 2995,
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg',
    category: 'Sports & Fitness',
    brand: 'Nike',
    rating: 4.4,
    reviews: 1876,
    description: 'Lightweight running shorts with moisture-wicking technology for comfortable workouts.',
    features: ['Dri-FIT Technology', 'Lightweight', 'Elastic Waistband', 'Reflective Details'],
    inStock: true,
    discount: 17
  },
  {
    id: '22',
    name: 'Adidas Training Shoes',
    price: 6999,
    originalPrice: 7999,
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg',
    category: 'Sports & Fitness',
    brand: 'Adidas',
    rating: 4.5,
    reviews: 2341,
    description: 'Versatile training shoes with superior grip and cushioning for all workout activities.',
    features: ['Superior Grip', 'Cushioned Sole', 'Breathable Upper', 'Durable Construction'],
    inStock: true,
    discount: 13
  },
  {
    id: '23',
    name: 'Puma Gym Bag',
    price: 1999,
    originalPrice: 2499,
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg',
    category: 'Sports & Fitness',
    brand: 'Puma',
    rating: 4.3,
    reviews: 987,
    description: 'Spacious gym bag with multiple compartments and durable construction for fitness enthusiasts.',
    features: ['Multiple Compartments', 'Durable Material', 'Adjustable Strap', 'Water Resistant'],
    inStock: true,
    discount: 20
  },
  {
    id: '24',
    name: 'Reebok Yoga Mat',
    price: 1499,
    originalPrice: 1999,
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg',
    category: 'Sports & Fitness',
    brand: 'Reebok',
    rating: 4.2,
    reviews: 1432,
    description: 'Premium yoga mat with non-slip surface and comfortable cushioning for yoga practice.',
    features: ['Non-Slip Surface', 'Comfortable Cushioning', 'Easy to Clean', 'Portable Design'],
    inStock: true,
    discount: 25
  },

  // Books & Media
  {
    id: '25',
    name: 'The Alchemist - Paulo Coelho',
    price: 299,
    originalPrice: 399,
    image: 'https://images.pexels.com/photos/159866/books-book-pages-read-literature-159866.jpeg',
    category: 'Books & Media',
    brand: 'HarperCollins',
    rating: 4.7,
    reviews: 5432,
    description: 'Bestselling novel about following your dreams and finding your personal legend.',
    features: ['Paperback Edition', '163 Pages', 'English Language', 'International Bestseller'],
    inStock: true,
    discount: 25
  },
  {
    id: '26',
    name: 'Rich Dad Poor Dad - Robert Kiyosaki',
    price: 399,
    originalPrice: 499,
    image: 'https://images.pexels.com/photos/159866/books-book-pages-read-literature-159866.jpeg',
    category: 'Books & Media',
    brand: 'Plata Publishing',
    rating: 4.6,
    reviews: 3876,
    description: 'Personal finance book teaching financial literacy and investment strategies.',
    features: ['Paperback Edition', '336 Pages', 'Financial Education', 'Bestselling Author'],
    inStock: true,
    discount: 20
  },
  {
    id: '27',
    name: 'Atomic Habits - James Clear',
    price: 449,
    originalPrice: 599,
    image: 'https://images.pexels.com/photos/159866/books-book-pages-read-literature-159866.jpeg',
    category: 'Books & Media',
    brand: 'Random House',
    rating: 4.8,
    reviews: 4321,
    description: 'Practical guide to building good habits and breaking bad ones for personal development.',
    features: ['Hardcover Edition', '320 Pages', 'Self-Help Category', 'New York Times Bestseller'],
    inStock: true,
    discount: 25
  },
  {
    id: '28',
    name: 'Bollywood Music Collection CD',
    price: 199,
    originalPrice: 299,
    image: 'https://images.pexels.com/photos/159866/books-book-pages-read-literature-159866.jpeg',
    category: 'Books & Media',
    brand: 'T-Series',
    rating: 4.3,
    reviews: 2156,
    description: 'Collection of popular Bollywood songs from recent hit movies and albums.',
    features: ['Audio CD', '20 Hit Songs', 'High Quality Audio', 'Latest Collection'],
    inStock: true,
    discount: 33
  },

  // Automotive
  {
    id: '29',
    name: 'Castrol GTX Engine Oil 5W-30',
    price: 2499,
    originalPrice: 2999,
    image: 'https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg',
    category: 'Automotive',
    brand: 'Castrol',
    rating: 4.5,
    reviews: 1876,
    description: 'Premium engine oil for superior engine protection and performance in all conditions.',
    features: ['5W-30 Grade', '4 Liter Pack', 'Engine Protection', 'All Weather Formula'],
    inStock: true,
    discount: 17
  },
  {
    id: '30',
    name: 'Bosch Car Battery 12V',
    price: 6999,
    originalPrice: 7999,
    image: 'https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg',
    category: 'Automotive',
    brand: 'Bosch',
    rating: 4.4,
    reviews: 987,
    description: 'Reliable car battery with long life and consistent performance for all vehicle types.',
    features: ['12V 65Ah', 'Maintenance Free', '3 Year Warranty', 'High Performance'],
    inStock: true,
    discount: 13
  },
  {
    id: '31',
    name: 'Michelin Car Tires 195/65 R15',
    price: 8999,
    originalPrice: 9999,
    image: 'https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg',
    category: 'Automotive',
    brand: 'Michelin',
    rating: 4.6,
    reviews: 1432,
    description: 'Premium car tires with excellent grip, durability, and fuel efficiency for safe driving.',
    features: ['195/65 R15 Size', 'Excellent Grip', 'Fuel Efficient', 'Long Lasting'],
    inStock: true,
    discount: 10
  },
  {
    id: '32',
    name: 'Car Dashboard Camera HD',
    price: 4999,
    originalPrice: 6999,
    image: 'https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg',
    category: 'Automotive',
    brand: 'Garmin',
    rating: 4.3,
    reviews: 2156,
    description: 'High definition dashboard camera for recording drives and ensuring road safety.',
    features: ['1080p HD Recording', 'Night Vision', 'Loop Recording', 'G-Sensor'],
    inStock: true,
    discount: 29
  },

  // Health & Wellness
  {
    id: '33',
    name: 'Whey Protein Powder 2kg',
    price: 3999,
    originalPrice: 4999,
    image: 'https://images.pexels.com/photos/40751/running-runner-long-distance-fitness-40751.jpeg',
    category: 'Health & Wellness',
    brand: 'Optimum Nutrition',
    rating: 4.5,
    reviews: 3421,
    description: 'Premium whey protein powder for muscle building and post-workout recovery.',
    features: ['25g Protein per Serving', '2kg Pack', 'Multiple Flavors', 'Fast Absorption'],
    inStock: true,
    discount: 20
  },
  {
    id: '34',
    name: 'Digital Blood Pressure Monitor',
    price: 2499,
    originalPrice: 2999,
    image: 'https://images.pexels.com/photos/40751/running-runner-long-distance-fitness-40751.jpeg',
    category: 'Health & Wellness',
    brand: 'Omron',
    rating: 4.4,
    reviews: 1876,
    description: 'Accurate digital blood pressure monitor for home health monitoring and tracking.',
    features: ['Digital Display', 'Memory Storage', 'Easy Operation', 'Clinically Validated'],
    inStock: true,
    discount: 17
  },
  {
    id: '35',
    name: 'Vitamin D3 Tablets',
    price: 599,
    originalPrice: 799,
    image: 'https://images.pexels.com/photos/40751/running-runner-long-distance-fitness-40751.jpeg',
    category: 'Health & Wellness',
    brand: 'Himalaya',
    rating: 4.3,
    reviews: 2876,
    description: 'Essential vitamin D3 supplement for bone health and immune system support.',
    features: ['60 Tablets', 'Natural Ingredients', 'Bone Health', 'Immune Support'],
    inStock: true,
    discount: 25
  },
  {
    id: '36',
    name: 'Digital Weighing Scale',
    price: 1999,
    originalPrice: 2499,
    image: 'https://images.pexels.com/photos/40751/running-runner-long-distance-fitness-40751.jpeg',
    category: 'Health & Wellness',
    brand: 'HealthSense',
    rating: 4.2,
    reviews: 1543,
    description: 'Accurate digital weighing scale with BMI calculation and memory storage features.',
    features: ['Digital Display', 'BMI Calculation', 'Memory Storage', '180kg Capacity'],
    inStock: true,
    discount: 20
  }
];

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(price);
};

export const getDiscountPercentage = (original: number, current: number): number => {
  return Math.round(((original - current) / original) * 100);
};